services:
  notary_url: "http://notary-service.build.10gen.cc:5000"

templates:
  deb:
    org: |
      Origin: bongodb
      Label: bongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/bongodb-org
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: BongoDB packages
    enterprise: |
      Origin: bongodb
      Label: bongodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/bongodb-enterprise
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: BongoDB packages
  index_page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ .Title }}</title>
     </head>

     <body>
       <table>
        <tr><td>
          <h1>{{ .Title }}</h1>
        </td></tr>

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>

        {{ range $fn := .Files }}
        <tr><td>
          <a href='{{ $fn }}'>{{ $fn }}</a>
        </td></tr>
        {{ end }}

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>


repos:

####################
#
# Community Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: org
    bucket: repo.bongodb.org
    repos:
      - yum/redhat/6/bongodb-org
      - yum/redhat/6Server/bongodb-org

  - name: rhel70
    type: rpm
    edition: org
    bucket: repo.bongodb.org
    repos:
      - yum/redhat/7/bongodb-org
      - yum/redhat/7Server/bongodb-org

  - name: amazon
    type: rpm
    edition: org
    bucket: repo.bongodb.org
    repos:
      - yum/amazon/2013.03/bongodb-org

  - name: suse11
    type: rpm
    edition: org
    bucket: repo.bongodb.org
    repos:
      - zypper/suse/11/bongodb-org

  - name: suse12
    type: rpm
    edition: org
    bucket: repo.bongodb.org
    repos:
      - zypper/suse/12/bongodb-org

  - name: debian81
    type: deb
    code_name: "jessie"
    bucket: repo.bongodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/jessie/bongodb-org

  - name: debian71
    type: deb
    code_name: "wheezy"
    bucket: repo.bongodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/wheezy/bongodb-org

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: org
    bucket: repo.bongodb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/precise/bongodb-org

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: org
    bucket: repo.bongodb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/trusty/bongodb-org

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: org
    bucket: repo.bongodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/bongodb-org

####################
#
# Enterprise Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - yum/redhat/6/bongodb-enterprise
      - yum/redhat/6Server/bongodb-enterprise

  - name: rhel70
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - yum/redhat/7/bongodb-enterprise
      - yum/redhat/7Server/bongodb-enterprise

  - name: rhel71
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - yum/redhat/7/bongodb-enterprise
      - yum/redhat/7Server/bongodb-enterprise

  - name: rhel72
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - yum/redhat/7/bongodb-enterprise
      - yum/redhat/7Server/bongodb-enterprise

  - name: amazon
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - yum/amazon/2013.03/bongodb-enterprise

  - name: suse11
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - zypper/suse/11/bongodb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo.bongodb.com
    repos:
      - zypper/suse/12/bongodb-enterprise

  - name: debian81
    type: deb
    edition: enterprise
    code_name: "jessie"
    bucket: repo.bongodb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/jessie/bongodb-enterprise

  - name: debian71
    type: deb
    code_name: "wheezy"
    edition: enterprise
    bucket: repo.bongodb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/wheezy/bongodb-enterprise

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: enterprise
    bucket: repo.bongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/precise/bongodb-enterprise

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: enterprise
    bucket: repo.bongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/trusty/bongodb-enterprise

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: enterprise
    bucket: repo.bongodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/bongodb-enterprise
